[package]
name = "delve"
version = "0.1.0"
edition = "2024"

[dependencies]
delve-macros = { version = "0.1.0", path = "../delve-macros" }
delve-shared = { version = "0.1.0", path = "../delve-shared" }
chrono = { workspace = true }
crossterm = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(profiling_enabled)'] }
